map $http_user_agent $is_social_crawler {
    default                         0;
    "~*LinkedInBot"                 1;
    "~*facebookexternalhit"         1;
    "~*Twitterbot"                  1;
    "~*Slackbot-LinkExpanding"      1;
    "~*WhatsApp"                    1;
    "~*TelegramBot"                 1;
    "~*Discordbot"                  1;
    "~*Pinterest"                   1;
}
