-- Product comparison table CMS rows (ai-analyzer page)
-- Column headers
INSERT INTO page_content (page, section, key, label, value, type) VALUES
  ('ai-analyzer', 'comparison', 'col1',        'Column 1 Name',              'AI-100Vet',        'text'),
  ('ai-analyzer', 'comparison', 'col2',        'Column 2 Name',              'AI-100Vet Elite',  'text'),
  ('ai-analyzer', 'comparison', 'col3',        'Column 3 Name',              'AI-80Vet',         'text'),
  ('ai-analyzer', 'comparison', 'description', 'Section Description',        'Compare models across sample types and species support to match your clinic''s needs.', 'text'),
-- Category 1: Sample Types
  ('ai-analyzer', 'comparison', 'cat1',        'Category 1 Name',            'Sample Types',     'text'),
  ('ai-analyzer', 'comparison', 'cat1_r1',     'Cat 1 Row 1 Name',           'Blood',            'text'),
  ('ai-analyzer', 'comparison', 'cat1_r1_c1',  'Blood - AI-100Vet',          '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r1_c2',  'Blood - AI-100Vet Elite',    '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r1_c3',  'Blood - AI-80Vet',           '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r2',     'Cat 1 Row 2 Name',           'Feces',            'text'),
  ('ai-analyzer', 'comparison', 'cat1_r2_c1',  'Feces - AI-100Vet',          '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r2_c2',  'Feces - AI-100Vet Elite',    '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r2_c3',  'Feces - AI-80Vet',           '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r3',     'Cat 1 Row 3 Name',           'Urine',            'text'),
  ('ai-analyzer', 'comparison', 'cat1_r3_c1',  'Urine - AI-100Vet',          '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r3_c2',  'Urine - AI-100Vet Elite',    '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r3_c3',  'Urine - AI-80Vet',           '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r4',     'Cat 1 Row 4 Name',           'Fluid',            'text'),
  ('ai-analyzer', 'comparison', 'cat1_r4_c1',  'Fluid - AI-100Vet',          '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r4_c2',  'Fluid - AI-100Vet Elite',    '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat1_r4_c3',  'Fluid - AI-80Vet',           '/',                'text'),
-- Category 2: Species Support
  ('ai-analyzer', 'comparison', 'cat2',        'Category 2 Name',            'Species Support',  'text'),
  ('ai-analyzer', 'comparison', 'cat2_r1',     'Cat 2 Row 1 Name',           'Companion & Small Mammals', 'text'),
  ('ai-analyzer', 'comparison', 'cat2_r1_c1',  'Companion - AI-100Vet',      '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r1_c2',  'Companion - AI-100Vet Elite','+',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r1_c3',  'Companion - AI-80Vet',       '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r2',     'Cat 2 Row 2 Name',           'Avian',            'text'),
  ('ai-analyzer', 'comparison', 'cat2_r2_c1',  'Avian - AI-100Vet',          '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r2_c2',  'Avian - AI-100Vet Elite',    '/',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r2_c3',  'Avian - AI-80Vet',           '/',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r3',     'Cat 2 Row 3 Name',           'Reptile',          'text'),
  ('ai-analyzer', 'comparison', 'cat2_r3_c1',  'Reptile - AI-100Vet',        '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r3_c2',  'Reptile - AI-100Vet Elite',  '/',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r3_c3',  'Reptile - AI-80Vet',         '/',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r4',     'Cat 2 Row 4 Name',           'Livestock & Large Animals', 'text'),
  ('ai-analyzer', 'comparison', 'cat2_r4_c1',  'Livestock - AI-100Vet',      '+',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r4_c2',  'Livestock - AI-100Vet Elite','/',                'text'),
  ('ai-analyzer', 'comparison', 'cat2_r4_c3',  'Livestock - AI-80Vet',       '/',                'text')
ON CONFLICT (page, section, key) DO NOTHING;
