-- ─────────────────────────────────────────────────────────────────────────────
-- Page content for application pages and individual product pages
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO public.page_content (page, section, key, label, value, type) VALUES

-- ─── BLOOD ANALYSIS (/applications/blood) ────────────────────────────────────
('blood', 'hero',            'title',         'Page Title',          'Blood Analysis',                                                                                                                                                                                                                 'text'),
('blood', 'hero',            'subtitle',      'Page Subtitle',       'The most extensive Complete Blood Count (CBC) in veterinary medicine',                                                                                                                                                           'text'),
('blood', 'overview',        'badge',         'Section Badge',       'Blood Analysis',                                                                                                                                                                                                                 'text'),
('blood', 'overview',        'body',          'Section Body',        'Awalife delivers a clinic-ready blood smear workflow with AI-assisted recognition and counting. Results are reported with review-ready images and quantitative outputs, enabling consistent decisions across teams and sites.',      'text'),
('blood', 'overview',        'cta_primary',   'Primary CTA',         'Contact us',                                                                                                                                                                                                                     'text'),
('blood', 'overview',        'cta_secondary', 'Secondary CTA',       'See it in action',                                                                                                                                                                                                               'text'),
('blood', 'classification',  'badge',         'Section Badge',       'AI-Powered Classification',                                                                                                                                                                                                      'text'),
('blood', 'classification',  'subtitle',      'Section Subtitle',    'Powered by our latest AI model, continuously improving with regular updates.',                                                                                                                                                   'text'),
('blood', 'clinical_images', 'badge',         'Section Badge',       'Clinical Images',                                                                                                                                                                                                                'text'),
('blood', 'clinical_images', 'subtitle',      'Section Subtitle',    'Review your report and verify the images with confidence - and tap into Awalife''s clinical specialists whenever needed.',                                                                                                       'text'),
('blood', 'cta',             'title',         'CTA Title',           'Interested in Our Products?',                                                                                                                                                                                                    'text'),
('blood', 'cta',             'body',          'CTA Body',            'Contact our team for pricing, demonstrations, and technical specifications tailored to your clinic''s needs.',                                                                                                                   'text'),

-- ─── FECES ANALYSIS (/applications/feces) ────────────────────────────────────
('feces', 'hero',            'title',         'Page Title',          'Feces Analysis',                                                                                                                                                                                                                 'text'),
('feces', 'hero',            'subtitle',      'Page Subtitle',       'From repetitive inefficiency to simple efficiency',                                                                                                                                                                              'text'),
('feces', 'overview',        'badge',         'Section Badge',       'Fecal Analysis',                                                                                                                                                                                                                 'text'),
('feces', 'overview',        'body',          'Section Body',        'Awalife streamlines fecal screening with a slide-free workflow and two sampling options, delivering review-ready images and actionable findings in under 30 minutes - designed for consistent interpretation and documentation.',  'text'),
('feces', 'overview',        'cta_primary',   'Primary CTA',         'Contact us',                                                                                                                                                                                                                     'text'),
('feces', 'overview',        'cta_secondary', 'Secondary CTA',       'See it in action',                                                                                                                                                                                                               'text'),
('feces', 'classification',  'badge',         'Section Badge',       'AI-Powered Analysis',                                                                                                                                                                                                            'text'),
('feces', 'classification',  'subtitle',      'Section Subtitle',    'Powered by our latest AI model, continuously improving with regular updates.',                                                                                                                                                   'text'),
('feces', 'clinical_images', 'badge',         'Section Badge',       'Clinical Images',                                                                                                                                                                                                                'text'),
('feces', 'clinical_images', 'subtitle',      'Section Subtitle',    'Review your report and verify the images with confidence - and tap into Awalife''s clinical specialists whenever needed.',                                                                                                       'text'),
('feces', 'cta',             'title',         'CTA Title',           'Interested in Our Products?',                                                                                                                                                                                                    'text'),
('feces', 'cta',             'body',          'CTA Body',            'Contact our team for pricing, demonstrations, and technical specifications tailored to your clinic''s needs.',                                                                                                                   'text'),

-- ─── URINE SEDIMENT ANALYSIS (/applications/urine) ───────────────────────────
('urine', 'hero',            'title',         'Page Title',          'Urine Sediment Analysis',                                                                                                                                                                                                        'text'),
('urine', 'hero',            'subtitle',      'Page Subtitle',       'Comprehensive results. Expedited clinical decisions.',                                                                                                                                                                           'text'),
('urine', 'overview',        'badge',         'Section Badge',       'Urine Analysis',                                                                                                                                                                                                                 'text'),
('urine', 'overview',        'body',          'Section Body',        'Awalife brings a repeatable, clinic-ready workflow for urine formed elements. From sample processing to imaging and AI-assisted recognition, results are delivered as review-ready reports with images and quantified outputs, helping teams work faster and more consistently.', 'text'),
('urine', 'overview',        'cta_primary',   'Primary CTA',         'Contact us',                                                                                                                                                                                                                     'text'),
('urine', 'overview',        'cta_secondary', 'Secondary CTA',       'See it in action',                                                                                                                                                                                                               'text'),
('urine', 'classification',  'badge',         'Section Badge',       'AI-Powered Analysis',                                                                                                                                                                                                            'text'),
('urine', 'classification',  'subtitle',      'Section Subtitle',    'Powered by our latest AI model, continuously improving with regular updates.',                                                                                                                                                   'text'),
('urine', 'clinical_images', 'badge',         'Section Badge',       'Clinical Images',                                                                                                                                                                                                                'text'),
('urine', 'clinical_images', 'subtitle',      'Section Subtitle',    'Review your report and verify the images with confidence - and tap into Awalife''s clinical specialists whenever needed.',                                                                                                       'text'),
('urine', 'cta',             'title',         'CTA Title',           'Interested in Our Products?',                                                                                                                                                                                                    'text'),
('urine', 'cta',             'body',          'CTA Body',            'Contact our team for pricing, demonstrations, and technical specifications tailored to your clinic''s needs.',                                                                                                                   'text'),

-- ─── PLEURAL EFFUSION (/applications/pleural-effusion) ───────────────────────
('pleural', 'hero',            'title',         'Page Title',          'Pleural Effusion Analysis',                                                                                                                                                                                                    'text'),
('pleural', 'hero',            'subtitle',      'Page Subtitle',       'Comprehensive body fluid cytology for accurate diagnosis',                                                                                                                                                                     'text'),
('pleural', 'overview',        'badge',         'Section Badge',       'Body Fluid Analysis',                                                                                                                                                                                                          'text'),
('pleural', 'overview',        'body',          'Section Body',        'Awalife helps standardize pleural and abdominal effusion review by combining high-quality microscopy imaging with AI-assisted morphology recognition. Results are delivered as a review-ready report with images and structured findings, including up to 19 reportable items.', 'text'),
('pleural', 'overview',        'cta_primary',   'Primary CTA',         'Contact us',                                                                                                                                                                                                                   'text'),
('pleural', 'classification',  'badge',         'Section Badge',       'Cell Counting',                                                                                                                                                                                                                'text'),
('pleural', 'classification',  'subtitle',      'Section Body',        'In many workflows, TNCC is approximated using total WBC counts, which can overlook non-WBC formed elements and introduce variability across operators and methods. Awalife takes a morphology-first approach: it captures true-to-life microscopy images and performs morphology-based TNCC enumeration, counting nucleated cells based on what is actually present in the sample. The result is a review-ready output with image evidence, supporting more consistent TNCC reporting and clearer clinical communication for pleural and abdominal effusions.', 'text'),
('pleural', 'clinical_images', 'badge',         'Section Badge',       'Image Quality',                                                                                                                                                                                                                'text'),
('pleural', 'clinical_images', 'subtitle',      'Section Subtitle',    'Review your report and verify the images with confidence - and tap into Awalife''s clinical specialists whenever needed.',                                                                                                     'text'),
('pleural', 'cta',             'title',         'CTA Title',           'Interested in Our Products?',                                                                                                                                                                                                  'text'),
('pleural', 'cta',             'body',          'CTA Body',            'Contact our team for pricing, demonstrations, and technical specifications tailored to your clinic''s needs.',                                                                                                                 'text'),

-- ─── EXOTIC ANIMALS (/applications/exotic-animals) ───────────────────────────
('exotic', 'hero',     'title',         'Page Title',          'Exotics, Small Mammals & Large Animals',                                                                                                                                                                                               'text'),
('exotic', 'hero',     'subtitle',      'Page Subtitle',       'Supporting more species with review-ready morphology',                                                                                                                                                                                 'text'),
('exotic', 'overview', 'badge',         'Section Badge',       'Multi-Species Support',                                                                                                                                                                                                                'text'),
('exotic', 'overview', 'body',          'Section Body',        'Awalife extends morphology-first, AI-assisted analysis beyond dogs and cats—supporting a wider range of species with review-ready reports that combine images and quantitative results. Capabilities may vary by species and sample type.', 'text'),
('exotic', 'overview', 'cta_primary',   'Primary CTA',         'Contact us',                                                                                                                                                                                                                          'text'),
('exotic', 'cta',      'title',         'CTA Title',           'Interested in Our Products?',                                                                                                                                                                                                          'text'),
('exotic', 'cta',      'body',          'CTA Body',            'Contact our team for pricing, demonstrations, and technical specifications tailored to your clinic''s needs.',                                                                                                                         'text'),

-- ─── PRODUCT PAGES ───────────────────────────────────────────────────────────

-- AI Analyzer (ai-analyzer)
('ai-analyzer',      'hero',     'name',        'Product Name',        'AI Series Morphology Analyzer',                                                                                                                                                                                               'text'),
('ai-analyzer',      'hero',     'tagline',     'Product Tagline',     'AI-powered morphology analyzer for veterinary diagnostics',                                                                                                                                                                   'text'),
('ai-analyzer',      'overview', 'description', 'Product Description', 'Awalife AI Series Morphology Analyzer is an AI-powered veterinary platform for four sample types: blood, urine, feces, and body fluids. It combines multi-focus imaging, rapid liquid-based staining, AI-assisted morphology recognition and counting, and report generation with review-ready images and quantitative results. The system also supports an expandable parameter set for deeper clinical insight.', 'text'),

-- AI-100Vet Elite (ai-100vet-elite)
('ai-100vet-elite',  'hero',     'name',        'Product Name',        'AI-100Vet Elite Morphological Analyzer',                                                                                                                                                                                      'text'),
('ai-100vet-elite',  'hero',     'tagline',     'Product Tagline',     'Premium AI-Powered Diagnostics for Cats & Dogs',                                                                                                                                                                             'text'),
('ai-100vet-elite',  'overview', 'description', 'Product Description', 'AI-100Vet Elite Morphological Analyzer is an AI-powered diagnostic device for cats and dogs, capable of automatically analyzing three sample types: blood, feces, and urine. Featuring microfluidic automated smearing, rapid liquid-based staining, and AI-powered recognition with auto-generated diagnostic reports.', 'text'),

-- AI-100Vet (ai-100vet)
('ai-100vet',        'hero',     'name',        'Product Name',        'AI-100Vet Morphological Analyzer',                                                                                                                                                                                            'text'),
('ai-100vet',        'hero',     'tagline',     'Product Tagline',     'Multi-Species Intelligent Diagnostics',                                                                                                                                                                                       'text'),
('ai-100vet',        'overview', 'description', 'Product Description', 'AI-100Vet Morphological Analyzer is an intelligent diagnostic device tailored for veterinary applications. It supports automatic analysis of four sample types including blood, feces, urine sediment, and pleural fluid, meeting the diverse clinical needs of more than 10 species including dogs, cats, rabbits, turtles, birds, parrots, snakes, and lizards.', 'text'),

-- AI-80Vet (ai-80vet)
('ai-80vet',         'hero',     'name',        'Product Name',        'AI-80Vet Morphological Analyzer',                                                                                                                                                                                             'text'),
('ai-80vet',         'hero',     'tagline',     'Product Tagline',     'Configurable Testing for Diverse Needs',                                                                                                                                                                                      'text'),
('ai-80vet',         'overview', 'description', 'Product Description', 'AI-80Vet Morphological Analyzer is an intelligent diagnostic device tailored for veterinary applications, which offers configurable sample testing functions to meet diverse veterinary needs. Supports comprehensive blood, feces, and urine analysis with advanced AI recognition.', 'text'),

-- Microscope (microscope)
('microscope',       'hero',     'name',        'Product Name',        'DM-03 Microscope Workstation',                                                                                                                                                                                                'text'),
('microscope',       'hero',     'tagline',     'Product Tagline',     'Smarter imaging and effortless operation',                                                                                                                                                                                    'text'),
('microscope',       'overview', 'description', 'Product Description', 'Awalife Microscope Workstation is more than a standard veterinary microscope—it brings imaging, measurement, cell counting, and documentation into one streamlined workflow. With built-in software to add scale bars, annotate findings, and generate a report in one click, it helps clinics capture consistent results with less manual effort.', 'text'),

-- DM-03 (dm-03)
('dm-03',            'hero',     'name',        'Product Name',        'DM-03 Microscope Workstation',                                                                                                                                                                                                'text'),
('dm-03',            'hero',     'tagline',     'Product Tagline',     'Smarter imaging and effortless operation',                                                                                                                                                                                    'text'),
('dm-03',            'overview', 'description', 'Product Description', 'Awalife Microscope Workstation is more than a standard veterinary microscope—it brings imaging, measurement, cell counting, and documentation into one streamlined workflow. With built-in software to add scale bars, annotate findings, and generate a report in one click, it helps clinics capture consistent results with less manual effort.', 'text')

ON CONFLICT (page, section, key) DO NOTHING;
